name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ./          # корневая папка проекта
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ballistics-calc-apk
          path: ${{ steps.buildozer.outputs.filename }}
